// AUTO-GENERATED by scripts/build-images.ts -- DO NOT EDIT
// Generated: 2026-03-19T13:49:31.305Z

export type ImageSource = number; // Metro require() returns a number (asset ID)

export interface RecipeImages {
  cover: ImageSource | null;
  steps: (ImageSource | null)[];
}

const registry: Record<string, RecipeImages> = {
  "adana-kebap": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "asure": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "baklava": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "borek": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "cig-kofte": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "coban-salatasi": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "dolma": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "ezme": {
    cover: null,
    steps: [
      null,
      null,
    ],
  },
  "gozleme": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "helva": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "humus": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "imam-bayildi": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "ispanak-corbasi": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "karniyarik": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "kazandibi": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "kisir": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "kofte": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "lahana-sarmasi": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "menemen": {
    cover: require("./images/menemen-cover.webp"),
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "mercimek-corbasi": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "pilav": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "pogaca": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "sigara-boregi": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "simit": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "sucuklu-yumurta": {
    cover: null,
    steps: [
      null,
      null,
    ],
  },
  "sutlac": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "tarator": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "tarhana-corbasi": {
    cover: null,
    steps: [
      null,
      null,
      null,
    ],
  },
  "tavuk-sote": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
  "yayla-corbasi": {
    cover: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
  },
};

export function getRecipeImages(recipeId: string): RecipeImages {
  return registry[recipeId] ?? { cover: null, steps: [] };
}
