// AUTO-GENERATED by scripts/build-images.ts -- DO NOT EDIT
// Generated: 2026-03-19T17:14:10.591Z

export type ImageSource = number; // Metro require() returns a number (asset ID)

export interface RecipeImages {
  cover: ImageSource | null;
  coverBlurhash: string | null;
  steps: (ImageSource | null)[];
  stepBlurhashes: (string | null)[];
}

const registry: Record<string, RecipeImages> = {
  "adana-kebap": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "asure": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "baklava": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "borek": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "cig-kofte": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "coban-salatasi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "dolma": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "ezme": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
    ],
  },
  "gozleme": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "helva": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "humus": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "imam-bayildi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "ispanak-corbasi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "karniyarik": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "kazandibi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "kisir": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "kofte": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "lahana-sarmasi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "menemen": {
    cover: require("./images/menemen-cover.webp"),
    coverBlurhash: "LIIy?#}AH[?GxtI:,?xF02BSpHE2",
    steps: [
      require("./images/menemen-step-01.webp"),
      require("./images/menemen-step-02.webp"),
      require("./images/menemen-step-03.webp"),
      require("./images/menemen-step-04.webp"),
      require("./images/menemen-step-05.webp"),
    ],
    stepBlurhashes: [
      "LIIy?#}AH[?GxtI:,?xF02BSpHE2",
      "LEGtyW-.tT%g~TR558%1050gv|%K",
      "L7H,9T^O3D$+}?D%IUE20qOZ#9Xl",
      "L8J5.7:jPVVs_M0eXT572xOXWY%2",
      "L8J5_F}n17ER^i9ZsAE20F9|-m%L",
    ],
  },
  "mercimek-corbasi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "pilav": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "pogaca": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "sigara-boregi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "simit": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "sucuklu-yumurta": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
    ],
  },
  "sutlac": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
      null,
    ],
  },
  "tarator": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "tarhana-corbasi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
    ],
  },
  "tavuk-sote": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
  "yayla-corbasi": {
    cover: null,
    coverBlurhash: null,
    steps: [
      null,
      null,
      null,
      null,
    ],
    stepBlurhashes: [
      null,
      null,
      null,
      null,
    ],
  },
};

export function getRecipeImages(recipeId: string): RecipeImages {
  return registry[recipeId] ?? { cover: null, coverBlurhash: null, steps: [], stepBlurhashes: [] };
}
